services:
  backend:
    build:
      context: ./backend
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - mongo
    volumes:
      - ./backend:/app
    networks:
      - chatbot-net

  frontend:
    build:
      context: ./frontend
    container_name: chatbot_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - chatbot-net

  ngrok:
    image: ngrok/ngrok:latest
    container_name: chatbot_ngrok
    command: http frontend:3000
    env_file:
      - ./ngrok/.env
    depends_on:
      - frontend
    networks:
      - chatbot-net

  postgres:
    image: postgres:15
    container_name: chatbot_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devmode123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatbot-net

  mongo:
    image: mongo:6
    container_name: chatbot_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - chatbot-net

volumes:
  postgres_data:
  mongo_data:

networks:
  chatbot-net:
    driver: bridge
