# utils/metricas.py

# Mapeamento validado das colunas reais do banco com labels explicativos
METRICAS_VALIDAS = {
    "populacao": "População Total",
    "pib_per_capita": "PIB per Capita",
    "matriculas_infantil": "Matrículas - Educação Infantil",
    "matriculas_fundamental": "Matrículas - Ensino Fundamental",
    "matriculas_medio": "Matrículas - Ensino Médio",
    "matriculas_eja": "Matrículas - EJA",
    "matriculas_especial": "Matrículas - Educação Especial",
    "matriculas_tecnico": "Matrículas - Curso Técnico",
    "turmas_infantil": "Turmas - Educação Infantil",
    "turmas_fundamental": "Turmas - Ensino Fundamental",
    "turmas_medio": "Turmas - Ensino Médio",
    "turmas_eja": "Turmas - EJA",
    "turmas_especial": "Turmas - Educação Especial",
    "turmas_tecnico": "Turmas - Curso Técnico",
    "docentes_infantil": "Docentes - Educação Infantil",
    "docentes_fundamental": "Docentes - Ensino Fundamental",
    "docentes_medio": "Docentes - Ensino Médio",
    "docentes_eja": "Docentes - EJA",
    "docentes_especial": "Docentes - Educação Especial",
    "docentes_tecnico": "Docentes - Curso Técnico",
    "escolas_infantil": "Escolas - Educação Infantil",
    "escolas_fundamental": "Escolas - Ensino Fundamental",
    "escolas_medio": "Escolas - Ensino Médio",
    "escolas_eja": "Escolas - EJA",
    "escolas_especial": "Escolas - Educação Especial",
    "escolas_tecnico": "Escolas - Curso Técnico",
    "infra_basica_biblioteca": "Infraestrutura - Bibliotecas (Educação Básica)",
    "infra_basica_lab_ciencias": "Infraestrutura - Lab. Ciências (Educação Básica)",
    "infra_basica_lab_informatica": "Infraestrutura - Lab. Informática (Educação Básica)",
    "infra_basica_cozinha": "Infraestrutura - Cozinhas (Educação Básica)",
    "infra_basica_refeitorio": "Infraestrutura - Refeitórios (Educação Básica)",
    "infra_basica_quadra_esportes": "Infraestrutura - Quadras (Educação Básica)",
    "infra_basica_internet": "Infraestrutura - Internet (Educação Básica)",
    "infra_basica_acessibilidade_rampas": "Infraestrutura - Acessibilidade (Educação Básica)",
    "prof_basica_professores_pedagogia": "Professores com Formação Pedagógica",
    "prof_basica_coordenadores": "Coordenadores Pedagógicos",
    "prof_basica_monitores": "Monitores Educacionais",
    "cursos_tecnicos_ofertados": "Cursos Técnicos Ofertados"
}

# Heurística simples baseada em palavras-chave
HEURISTICAS = {
    "população": "populacao",
    "habitantes": "populacao",
    "total de pessoas": "populacao",
    "quantidade de habitantes": "populacao",
    "número de habitantes": "populacao",
    "demografia": "populacao",
    "pib": "pib_per_capita",
    "renda": "pib_per_capita",
    "renda média": "pib_per_capita",
    "matrículas": "matriculas_fundamental",
    "ensino médio": "matriculas_medio",
    "educação infantil": "matriculas_infantil",
    "escolas": "escolas_fundamental",
    "biblioteca": "infra_basica_biblioteca",
    "bibliotecas": "infra_basica_biblioteca",
    "quadra": "infra_basica_quadra_esportes",
    "quadras": "infra_basica_quadra_esportes",
    "cozinha": "infra_basica_cozinha",
    "internet": "infra_basica_internet",
    "laboratório": "infra_basica_lab_informatica",
    "laboratórios": "infra_basica_lab_informatica",
    "curso técnico": "cursos_tecnicos_ofertados",
    "cursos técnicos": "cursos_tecnicos_ofertados",
    "técnico": "cursos_tecnicos_ofertados"
}
